/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface LendingInterface extends utils.Interface {
  functions: {
    "borrower()": FunctionFragment;
    "collateralAmount()": FunctionFragment;
    "collateralToken()": FunctionFragment;
    "getLatestPrice()": FunctionFragment;
    "lend()": FunctionFragment;
    "loan()": FunctionFragment;
    "loanAmount()": FunctionFragment;
    "loanDuration()": FunctionFragment;
    "loanToken()": FunctionFragment;
    "makeLoanRequest(address,uint256,address,uint256,uint256,uint256)": FunctionFragment;
    "payoffAmount()": FunctionFragment;
    "storeLatestPrice()": FunctionFragment;
    "storedPrice()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "borrower"
      | "collateralAmount"
      | "collateralToken"
      | "getLatestPrice"
      | "lend"
      | "loan"
      | "loanAmount"
      | "loanDuration"
      | "loanToken"
      | "makeLoanRequest"
      | "payoffAmount"
      | "storeLatestPrice"
      | "storedPrice"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "borrower", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "collateralAmount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "collateralToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getLatestPrice",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "lend", values?: undefined): string;
  encodeFunctionData(functionFragment: "loan", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "loanAmount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "loanDuration",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "loanToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "makeLoanRequest",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "payoffAmount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "storeLatestPrice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "storedPrice",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "borrower", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "collateralAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "collateralToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLatestPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "lend", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "loan", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "loanAmount", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "loanDuration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "loanToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "makeLoanRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "payoffAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "storeLatestPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "storedPrice",
    data: BytesLike
  ): Result;

  events: {
    "LoanRequestAccepted(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "LoanRequestAccepted"): EventFragment;
}

export interface LoanRequestAcceptedEventObject {
  loan: string;
}
export type LoanRequestAcceptedEvent = TypedEvent<
  [string],
  LoanRequestAcceptedEventObject
>;

export type LoanRequestAcceptedEventFilter =
  TypedEventFilter<LoanRequestAcceptedEvent>;

export interface Lending extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: LendingInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    borrower(overrides?: CallOverrides): Promise<[string]>;

    collateralAmount(overrides?: CallOverrides): Promise<[BigNumber]>;

    collateralToken(overrides?: CallOverrides): Promise<[string]>;

    getLatestPrice(overrides?: CallOverrides): Promise<[BigNumber]>;

    lend(
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    loan(overrides?: CallOverrides): Promise<[string]>;

    loanAmount(overrides?: CallOverrides): Promise<[BigNumber]>;

    loanDuration(overrides?: CallOverrides): Promise<[BigNumber]>;

    loanToken(overrides?: CallOverrides): Promise<[string]>;

    makeLoanRequest(
      _collateralToken: PromiseOrValue<string>,
      _collateralAmount: PromiseOrValue<BigNumberish>,
      _loanToken: PromiseOrValue<string>,
      _loanAmount: PromiseOrValue<BigNumberish>,
      _payoffAmount: PromiseOrValue<BigNumberish>,
      _loanDuration: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    payoffAmount(overrides?: CallOverrides): Promise<[BigNumber]>;

    storeLatestPrice(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    storedPrice(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  borrower(overrides?: CallOverrides): Promise<string>;

  collateralAmount(overrides?: CallOverrides): Promise<BigNumber>;

  collateralToken(overrides?: CallOverrides): Promise<string>;

  getLatestPrice(overrides?: CallOverrides): Promise<BigNumber>;

  lend(
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  loan(overrides?: CallOverrides): Promise<string>;

  loanAmount(overrides?: CallOverrides): Promise<BigNumber>;

  loanDuration(overrides?: CallOverrides): Promise<BigNumber>;

  loanToken(overrides?: CallOverrides): Promise<string>;

  makeLoanRequest(
    _collateralToken: PromiseOrValue<string>,
    _collateralAmount: PromiseOrValue<BigNumberish>,
    _loanToken: PromiseOrValue<string>,
    _loanAmount: PromiseOrValue<BigNumberish>,
    _payoffAmount: PromiseOrValue<BigNumberish>,
    _loanDuration: PromiseOrValue<BigNumberish>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  payoffAmount(overrides?: CallOverrides): Promise<BigNumber>;

  storeLatestPrice(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  storedPrice(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    borrower(overrides?: CallOverrides): Promise<string>;

    collateralAmount(overrides?: CallOverrides): Promise<BigNumber>;

    collateralToken(overrides?: CallOverrides): Promise<string>;

    getLatestPrice(overrides?: CallOverrides): Promise<BigNumber>;

    lend(overrides?: CallOverrides): Promise<void>;

    loan(overrides?: CallOverrides): Promise<string>;

    loanAmount(overrides?: CallOverrides): Promise<BigNumber>;

    loanDuration(overrides?: CallOverrides): Promise<BigNumber>;

    loanToken(overrides?: CallOverrides): Promise<string>;

    makeLoanRequest(
      _collateralToken: PromiseOrValue<string>,
      _collateralAmount: PromiseOrValue<BigNumberish>,
      _loanToken: PromiseOrValue<string>,
      _loanAmount: PromiseOrValue<BigNumberish>,
      _payoffAmount: PromiseOrValue<BigNumberish>,
      _loanDuration: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    payoffAmount(overrides?: CallOverrides): Promise<BigNumber>;

    storeLatestPrice(overrides?: CallOverrides): Promise<void>;

    storedPrice(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {
    "LoanRequestAccepted(address)"(loan?: null): LoanRequestAcceptedEventFilter;
    LoanRequestAccepted(loan?: null): LoanRequestAcceptedEventFilter;
  };

  estimateGas: {
    borrower(overrides?: CallOverrides): Promise<BigNumber>;

    collateralAmount(overrides?: CallOverrides): Promise<BigNumber>;

    collateralToken(overrides?: CallOverrides): Promise<BigNumber>;

    getLatestPrice(overrides?: CallOverrides): Promise<BigNumber>;

    lend(
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    loan(overrides?: CallOverrides): Promise<BigNumber>;

    loanAmount(overrides?: CallOverrides): Promise<BigNumber>;

    loanDuration(overrides?: CallOverrides): Promise<BigNumber>;

    loanToken(overrides?: CallOverrides): Promise<BigNumber>;

    makeLoanRequest(
      _collateralToken: PromiseOrValue<string>,
      _collateralAmount: PromiseOrValue<BigNumberish>,
      _loanToken: PromiseOrValue<string>,
      _loanAmount: PromiseOrValue<BigNumberish>,
      _payoffAmount: PromiseOrValue<BigNumberish>,
      _loanDuration: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    payoffAmount(overrides?: CallOverrides): Promise<BigNumber>;

    storeLatestPrice(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    storedPrice(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    borrower(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    collateralAmount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    collateralToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getLatestPrice(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    lend(
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    loan(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    loanAmount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    loanDuration(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    loanToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    makeLoanRequest(
      _collateralToken: PromiseOrValue<string>,
      _collateralAmount: PromiseOrValue<BigNumberish>,
      _loanToken: PromiseOrValue<string>,
      _loanAmount: PromiseOrValue<BigNumberish>,
      _payoffAmount: PromiseOrValue<BigNumberish>,
      _loanDuration: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    payoffAmount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    storeLatestPrice(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    storedPrice(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
